//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CronExpressionDescriptor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CronExpressionDescriptor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 An error occured when generating the expression description.  Check the cron expression syntax. 的本地化字符串。
        /// </summary>
        internal static string AnErrorOccuredWhenGeneratingTheExpressionD {
            get {
                return ResourceManager.GetString("AnErrorOccuredWhenGeneratingTheExpressionD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 的本地化字符串。
        /// </summary>
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At  的本地化字符串。
        /// </summary>
        internal static string AtSpace {
            get {
                return ResourceManager.GetString("AtSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 at {0} 的本地化字符串。
        /// </summary>
        internal static string AtX0 {
            get {
                return ResourceManager.GetString("AtX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 at {0} minutes past the hour 的本地化字符串。
        /// </summary>
        internal static string AtX0MinutesPastTheHour {
            get {
                return ResourceManager.GetString("AtX0MinutesPastTheHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 at {0} seconds past the minute 的本地化字符串。
        /// </summary>
        internal static string AtX0SecondsPastTheMinute {
            get {
                return ResourceManager.GetString("AtX0SecondsPastTheMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 between {0} and {1} 的本地化字符串。
        /// </summary>
        internal static string BetweenX0AndX1 {
            get {
                return ResourceManager.GetString("BetweenX0AndX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , between day {0} and {1} of the month 的本地化字符串。
        /// </summary>
        internal static string ComaBetweenDayX0AndX1OfTheMonth {
            get {
                return ResourceManager.GetString("ComaBetweenDayX0AndX1OfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ,  every day  的本地化字符串。
        /// </summary>
        internal static string ComaEveryDay {
            get {
                return ResourceManager.GetString("ComaEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ,  every hour  的本地化字符串。
        /// </summary>
        internal static string ComaEveryHour {
            get {
                return ResourceManager.GetString("ComaEveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ,  every minute  的本地化字符串。
        /// </summary>
        internal static string ComaEveryMinute {
            get {
                return ResourceManager.GetString("ComaEveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , every {0} days 的本地化字符串。
        /// </summary>
        internal static string ComaEveryX0Days {
            get {
                return ResourceManager.GetString("ComaEveryX0Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , every {0} days of the week 的本地化字符串。
        /// </summary>
        internal static string ComaEveryX0DaysOfTheWeek {
            get {
                return ResourceManager.GetString("ComaEveryX0DaysOfTheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , every {0} months 的本地化字符串。
        /// </summary>
        internal static string ComaEveryX0Months {
            get {
                return ResourceManager.GetString("ComaEveryX0Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , every {0} years 的本地化字符串。
        /// </summary>
        internal static string ComaEveryX0Years {
            get {
                return ResourceManager.GetString("ComaEveryX0Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , on day {0} of the month 的本地化字符串。
        /// </summary>
        internal static string ComaOnDayX0OfTheMonth {
            get {
                return ResourceManager.GetString("ComaOnDayX0OfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , only in {0} 的本地化字符串。
        /// </summary>
        internal static string ComaOnlyInX0 {
            get {
                return ResourceManager.GetString("ComaOnlyInX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , only on {0} 的本地化字符串。
        /// </summary>
        internal static string ComaOnlyOnX0 {
            get {
                return ResourceManager.GetString("ComaOnlyOnX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , on the  的本地化字符串。
        /// </summary>
        internal static string ComaOnThe {
            get {
                return ResourceManager.GetString("ComaOnThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , on the last day of the month 的本地化字符串。
        /// </summary>
        internal static string ComaOnTheLastDayOfTheMonth {
            get {
                return ResourceManager.GetString("ComaOnTheLastDayOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , on the last weekday of the month 的本地化字符串。
        /// </summary>
        internal static string ComaOnTheLastWeekdayOfTheMonth {
            get {
                return ResourceManager.GetString("ComaOnTheLastWeekdayOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , on the last {0} of the month 的本地化字符串。
        /// </summary>
        internal static string ComaOnTheLastX0OfTheMonth {
            get {
                return ResourceManager.GetString("ComaOnTheLastX0OfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , on the {0} of the month 的本地化字符串。
        /// </summary>
        internal static string ComaOnTheX0OfTheMonth {
            get {
                return ResourceManager.GetString("ComaOnTheX0OfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , {0} through {1} 的本地化字符串。
        /// </summary>
        internal static string ComaX0ThroughX1 {
            get {
                return ResourceManager.GetString("ComaX0ThroughX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 every hour 的本地化字符串。
        /// </summary>
        internal static string EveryHour {
            get {
                return ResourceManager.GetString("EveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 every minute 的本地化字符串。
        /// </summary>
        internal static string EveryMinute {
            get {
                return ResourceManager.GetString("EveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every minute between {0} and {1} 的本地化字符串。
        /// </summary>
        internal static string EveryMinuteBetweenX0AndX1 {
            get {
                return ResourceManager.GetString("EveryMinuteBetweenX0AndX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 every second 的本地化字符串。
        /// </summary>
        internal static string EverySecond {
            get {
                return ResourceManager.GetString("EverySecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 every {0} hours 的本地化字符串。
        /// </summary>
        internal static string EveryX0Hours {
            get {
                return ResourceManager.GetString("EveryX0Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 every {0} minutes 的本地化字符串。
        /// </summary>
        internal static string EveryX0Minutes {
            get {
                return ResourceManager.GetString("EveryX0Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 every {0} seconds 的本地化字符串。
        /// </summary>
        internal static string EveryX0Seconds {
            get {
                return ResourceManager.GetString("EveryX0Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fifth 的本地化字符串。
        /// </summary>
        internal static string Fifth {
            get {
                return ResourceManager.GetString("Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 first 的本地化字符串。
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 first weekday 的本地化字符串。
        /// </summary>
        internal static string FirstWeekday {
            get {
                return ResourceManager.GetString("FirstWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 forth 的本地化字符串。
        /// </summary>
        internal static string Forth {
            get {
                return ResourceManager.GetString("Forth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minutes {0} through {1} past the hour 的本地化字符串。
        /// </summary>
        internal static string MinutesX0ThroughX1PastTheHour {
            get {
                return ResourceManager.GetString("MinutesX0ThroughX1PastTheHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 second 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 seconds {0} through {1} past the minute 的本地化字符串。
        /// </summary>
        internal static string SecondsX0ThroughX1PastTheMinute {
            get {
                return ResourceManager.GetString("SecondsX0ThroughX1PastTheMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  and 的本地化字符串。
        /// </summary>
        internal static string SpaceAnd {
            get {
                return ResourceManager.GetString("SpaceAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  and  的本地化字符串。
        /// </summary>
        internal static string SpaceAndSpace {
            get {
                return ResourceManager.GetString("SpaceAndSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  {0} of the month 的本地化字符串。
        /// </summary>
        internal static string SpaceX0OfTheMonth {
            get {
                return ResourceManager.GetString("SpaceX0OfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 third 的本地化字符串。
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 weekday nearest day {0} 的本地化字符串。
        /// </summary>
        internal static string WeekdayNearestDayX0 {
            get {
                return ResourceManager.GetString("WeekdayNearestDayX0", resourceCulture);
            }
        }
    }
}
