name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-14, windows-latest]
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Run tests
      run: dotnet test test/Test.csproj
